### ISSUE TITLE
Error Report Component Check

### ISSUE THREAD

**Issue by lurkybeatz** [Smooth-E/install-renderware#2]
So i followed install-renderware guide step-by-step and carefully read all the instructions, but when i try to open the program an error message pops up. It reads "The Microsoft Forms objects are not installed. Please consult documentation for further information". What would be the correct solution to removing this error? Or is it not salvageable at this point?

**Comment by Smooth-E** [comment]
Hello. The only error I personally encountered was the "Enterprise host" error, which is solved by enabling 3D acceleration. Did you install the ActiveX Control Pad (setuppad.exe)? This is the only thing that comes to mind regardless your error.

There's a [post](https://answers.microsoft.com/en-us/xbox/forum/all/microsoft-forms-could-not-be-found-on-your-machine/57947eff-bf28-4809-a5be-e87c293a43be) on Microsoft Learn from 2021 describing the same error and it has no valuable responses.

Did you use the SP3 version of Windows XP ([linked](https://archive.org/details/WinXPProSP3x86) in the documentation)? Maybe there are some libraries missing in older versions (unlikely, because RenderWare is also compatible with Windows 95 as far as I remember).

**Comment by lurkybeatz** [comment]
Got it to work. I simply forgot to move the setuppad.exe from my main system and install it to the VM. Thanks for your help!

**Comment by Smooth-E** [comment]
You are welcome!
